### ISSUE TITLE
Datasets folder structure - how to name sub-folders

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/datasets#1]
How to name sub-folders? If using DOI or UUID for the dataset in GBIF would make the folder much more machine readable...?! However, also much less human readable.

If naming folders with the name of the data publishing organisation, would make the folder much more human readable and ease the loading of new or updated datasets. We plan to assign each dataset a new DOI in Zenodo - so perhaps the machine readable folder names here is less important?

**Comment by dagendresen** [comment]
Seems like GitHub - Zenodo archiving require each citable item to be in a separate repository:
https://guides.github.com/activities/citable-code/

**Comment by gbifnorway** [comment]
I definitely think that placing each "dataset" in a separate repository is the way to go, for a bunch of reasons (access control, performance, not having to check out a bunch of stuff you're not interested in etc). There *can* be some advantages to huge monorepos when they're made up of a bunch of smaller projects that all depend on one another, but for what we're doing here I think it makes more sense to set up a repository for each dataset.

As for naming, I think we should stick to relatively simple human readable names for the repositories themselves. If we want a machine readable "access point" we could do that through our resolver (or even set up a completely separate simple API to find the github URL from the dataset UUID and/or the DOI).

**Comment by dagendresen** [comment]
Agree. I have tried to create an archive for the NEF Lepidoptera dataset in a separate repository. However, moving the dataset in the GBIF IPT to a "meta-data" only set will clearly need some more attention... Such approaches does NOT seem to be supported.
